Pass integer and not floating point
ESMCI/cime pull request #3820
Opened 2021-01-04 22:12 UTC by adityakavalur

Even though the calculation results in an integer, it passes it as a floating point i.e. 2.0 instead of 2. I was encountering issue on Cori (NERSC)

[ Description of the changes in this Pull Request. It should be enough
information for someone not following this development to understand.
Lines should be wrapped at about 72 characters. Please also update
the CIME documentation, if necessary, in doc/source/rst and indicate
below if you need to have the gh-pages html regenerated.]

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

2021-01-04 23:06 UTC, jedwards4b requested changes
Thank you for the contribution.  I believe that the prefered way to do this is
        self.srun_binding = (smt_factor*max_mpitasks_per_node) // self.tasks_per_node

2021-01-05 14:34 UTC, adityakavalur commented
Thanks for the quick response. 
While '//' does do the floor calculation it still returns the value as floating point e.g. 10.0 // 5.0 = 2.0 and 10.0 // 3.0 = 3.0 in python3. This still causes issues with Slurm, let me know if anything is unclear.

2021-01-05 15:24 UTC, jedwards4b commented
In that case, I will accept the change.  Thanks again.

2021-01-05 15:25 UTC, jedwards4b approved these changes

2021-01-05 15:25 UTC, merged