Adds support of DATM_MODE=CLM1PT for ELM
ESMCI/cime pull request #3845
Opened 2021-02-04 02:01 UTC by bishtgautam

Modifications to support user-defined atmospheric forcing
with ELM.

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

2021-02-04 02:05 UTC, bishtgautam commented
The new code in [src/components/data_comps_mct/datm/cime_config/buildnml ](https://github.com/ESMCI/cime/pull/3845/files#diff-d404eb6de5990e8b29112276e0189e7a1635a024660d96e52f138e78d9e4dfe5R47) may not be an ideal solution, but I wanted to open this PR to get the conversation started on how to best accommodate these changes.

2021-02-04 14:59 UTC, jedwards4b approved these changes
I don't see any problems with this.

2021-02-04 17:11 UTC, bishtgautam commented
It seems I broke a test.

2021-02-04 19:12 UTC, jedwards4b commented
You did - do you know where to find the log?   I also notice that you didn't run scripts_regression_tests.py locally for this PR.   Can you please do that and update the initial comment of the conversation.

```
======================================================================
FAIL: test_pylint_src_components_data_comps_mct_datm_cime_config_buildnml (__main__.B_CheckCode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 3480, in test
    self.assertTrue(result == "", msg=result)
AssertionError: False is not true : ************* Module buildnml
W: 57, 0: Bad indentation. Found 13 spaces, expected 12 (bad-indentation)
W: 59, 0: Bad indentation. Found 13 spaces, expected 12 (bad-indentation)
W: 65, 0: Bad indentation. Found 13 spaces, expected 12 (bad-indentation)
W: 67, 0: Bad indentation. Found 13 spaces, expected 12 (bad-indentation)
```

2021-02-04 20:53 UTC, jgfouca requested changes

2021-02-04 20:53 UTC, jgfouca commented on src/components/data_comps_mct/datm/cime_config/buildnml
> +    if get_model() != "e3sm":
The code looks identical in both branches with the only difference being ELM vs CLM. You should capture this difference in a single string so the code can be reused.

2021-02-04 22:06 UTC, jedwards4b approved these changes
Better, thanks.

2021-02-18 19:44 UTC, rljacob commented
@jgfouca this should be merged if you're happy with it.

2021-02-18 20:12 UTC, jgfouca approved these changes

2021-02-18 20:12 UTC, merged