Update support for trigrid configuration where lnd is not on the atm grid
ESMCI/cime pull request #3853
Opened 2021-02-09 22:42 UTC by jonbob

Brings in changes to fix both the diagnostics and lnd2rof coupling for
trigrid configurations, where atm is on one grid, lnd and rof on
another, and ocn/ice on a third. Issues with this configuration were
discovered during E3SM testing, and these changes fix all uncovered 
issues.

Test suite: 
Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

2021-02-09 22:46 UTC, jedwards4b reviewed
Please document the testing you have done in the opening comment of the PR. 
Did you add any test for trigrid?

2021-02-09 22:58 UTC, jonbob commented
I didn't add any trigrid test, but tested in E3SM with several trigrid configurations as well as making sure it didn't change answers for non-trigrid cases. I'm not sure how much documentation you want from the E3SM side? Our initial tests showed the water budget was not closed for trigrid, so we came up with a patch to seq_diags. Runs with that patch showed an actual problem with lnd2rof coupling when they were on the same grid, so the rest of this PR fixes that. Does CESM run any of these configurations? We can wrap more of the changes with cime_model logic, if that helps

2021-02-09 23:43 UTC, billsacks commented
I had some discussion with @mvertens and @apcraig in 2015 on the issue of lfrac vs. lfrin which neither I nor anybody else ever followed up on. The result of that discussion was that we all felt that the actual error is that lfrin is used at all: we all felt at the time that we should drop most uses of lfrin (such as the normalization factor in lnd -> atm mapping) and use lfrac in its place. I'm sorry that I never opened an issue on this. This discussion was based on drawing and examining a lot of pictures of example grids, and not based on any empirical evidence from coupler diagnostics.

Here was my original email, which admittedly does not express a lot of confidence:

> Hi Tony and Mariana,
> 
> (Tony: I had a long conversation with Mariana yesterday about lfrin vs. lfrac, since I was still confused about the use of these two subtly different variables.)
> 
> I spent a couple of hours this morning working through some examples, where I was considering whether we should use lfrac or lfrin in the normalization when mapping from LND -> GLC. See section 3.2.3 in https://docs.google.com/document/d/144PZ63gwpz875U4EYEI7NuxnF__V955QJOxV9LcEAL0/edit# (starting on p. 14).
> 
> Based on these examples, I have convinced myself that:
> 
> (1) In order to conserve, we need to normalize using lfrac rather than lfrin in the LND -> GLC mapping.
> 
> (2) Moreover, normalization by lfrin in the LND -> ATM mapping breaks conservation, regardless of the normalization factor we choose for the LND -> GLC mapping.
> 
> Thus, I concluded based on this that lfrin should never be used for normalization. Its only purpose in the system should be to set lfrac when you're running without ice/ocean. So it should be a local variable in seq_frac_mct, never referenced outside of there.
> 
> 
> Do you agree with my assessment? I have based these examples on my latest understanding of lfrac and lfrin, but I am not at all confident of this understanding. So it would be really good to get an independent check by one of you.
> 
> If you agree with my assessment, I would propose the following:
> 
> (a) I use normalization by lfrac in my new code, even though it is inconsistent with other mappings, because it appears to be needed for conservation.
> 
> (b) In a separate set of changes, which can come before or after my LND <-> GLC changes, we replace lfrin normalization with lfrac normalization, in prep_atm_mod and prep_rof_mod.
> 
> 
> Bill

And here was Tony's reply, which gave me more confidence:


> This is what I was expecting.  When all we were doing is mapping land to atm,
> we could use lfrin.  It gave us better science and conserved.  That was easy.
> When we separated rtm and then added flooding, this became more complicated
> but still worked because neither of those coupling involved conservation with a
> third component.  But now that we are coupling to glc that does have conservation
> issues with other models (runoff, lnd, etc), I think we have to abandon lfrin completely
> as it not only breaks conservation for lnd-glc coupling but that interaction also
> makes the lfrin invalid for the other land mappings as well.
> 
> I agree with your plan (a) and (b) below.  I think we have no choice.
> 
> tony.........


Based on this, I would suggest that you see if changing lfrin to lfrac in prep_atm_mod and prep_rof_mod gives conservation according to the coupler diagnostics you've been looking at.

2021-02-09 23:45 UTC, billsacks commented
By the way: In CESM, trigrid is technically supported, but as far as I know, it is rarely if ever used for science. This is why we let this issue drop when it came up 6 years ago.

2021-02-09 23:57 UTC, jonbob commented
@billsacks - I should have said that Tony helped me with all this. For E3SM, it does fix conservation issues in the diagnostics, as well as ensure the cpl budget matches that inside the lnd model. Would it help for me to post some of those results?

2021-02-10 00:36 UTC, apcraig commented
This update fixes the conservation and budget diagnostics in trigrid configurations.  It also preserves the non-trigrid configurations bit-for-bit and imposes no new requirements on them.  A more general solution might be better, but it would require more effort and could have a significant impact on backwards compatibility.  One issue I'll call out is that definition of lfrin is different in trigrid and non-trigrid.  That would probably be the first thing that needs to get resolved and why I advocated getting rid of lfrin all-together many years ago.  But that might require that we fundamentally redefine lfrac in the land model and the atm model and impose new constraints on non-trigrid land fractions in the land model input.  Finally, the solution proposed here does not address any potential existing glc issues, those were not considered.  But non-trigrid configurations are unchanged, and I'm not sure how much testing has been done with trigrid with glc on.

2021-02-10 17:10 UTC, jonbob commented
Following up on @apcraig's comment, I haven't done any testing with GLC on. E3SM still doesn't really run much with active GLC.

2021-02-10 17:41 UTC, billsacks requested changes
Thank you for the explanation, @jonbob and @apcraig . Given your explanation, I am okay with this change, but @jonbob please fill out the PR template more completely, documenting all testing done (note that we expect at least the testing documented here: https://github.com/ESMCI/cime/wiki/Testing#changes-to-fortran-or-to-the-test-scripts-in-systemtests) and, importantly, documenting the configurations in which this changes answers.

2021-02-10 18:48 UTC, jgfouca commented
I'm running scripts_regression_tests now.

2021-02-10 19:07 UTC, jonbob commented
Thanks @jgfouca

2021-02-10 19:40 UTC, jgfouca commented
Tests passed.

2021-02-10 19:40 UTC, jgfouca approved these changes

2021-02-12 00:28 UTC, jgfouca commented
@billsacks , did @jonbob address your concern about documented testing?

2021-02-12 00:31 UTC, billsacks commented
In the answer changes section, I think it would be better to start with what DOES change answers and by how much (roundoff vs. climate changing). This line is very important to our process and listing it as bit-for-bit (even with a qualification) may lead to issues down the line for us.

2021-02-12 16:22 UTC, jonbob commented
@billsacks - I added more information about what changes to the description above, but if it has more detail than is appropriate I'm happy to move it to this discussion part. The idea is that the PR should be BFB for configurations with atm/lnd on the same grid but it is climate-changing for trigrid cases, but only because they are incorrect currently. As-is, the lnd model does not pass fields correctly to the rof, so over time it has a continuous uptake of water. In E3SM, this results in a steady decrease of sea surface height in the ocn.

2021-02-12 17:07 UTC, billsacks approved these changes
Thank you for updating the top-level description. This looks good now.

2021-02-12 21:24 UTC, merged

2021-02-12 21:31 UTC, jonbob commented
Thanks @jgfouca for shepherding this through

2021-02-18 18:45 UTC, jgfouca commented
@rljacob , is this ready to merge?

2021-02-18 19:43 UTC, rljacob commented
Its been merged to CIME.  You can update the cime module in E3SM anytime.

2021-02-18 20:11 UTC, jgfouca commented
@rljacob , apologies, my tab was in a stale state. I merged this 6 days ago :)