Rename GLC Greenland grid from "gland" to "gris"
ESMCI/cime pull request #3943
Opened 2021-04-27 22:09 UTC by billsacks

We are renaming both the grid long name and alias to "gris". For now we
are maintaining backwards compatibility with old
aliases ("_gl4"/"_gl20").

Test suite: Ran a subset of tests from the aux_glc test list:
```
ERS_Ly11.f09_g17_gris20.T1850Gg.cheyenne_gnu
ERS_Vnuopc_Ly11.f09_g17_gris20.T1850Gg.cheyenne_gnu
ERS_Ly7.f09_g17_gris4.T1850Gg.cheyenne_intel
ERS_Vnuopc_Ly7.f09_g17_gris4.T1850Gg.cheyenne_intel
ERI.f10_f10_mg37.I1850Clm50SpG.cheyenne_gnu.cism-test_coupling
ERI_Vnuopc.f10_f10_mg37.I1850Clm50SpG.cheyenne_gnu.cism-test_coupling
SMS_D.T31_g37_gris20.I1850Clm50SpG.cheyenne_gnu.cism-test_coupling
SMS_Vnuopc_D.T31_g37_gris20.I1850Clm50SpG.cheyenne_gnu.cism-test_coupling
```

Test baseline: cism2_1_78
Test namelist changes: Yes, due to new grid name
Test status: bit for bit

Fixes none

User interface changes?: N

Update gh-pages html (Y/N)?: N

2021-04-27 22:16 UTC, mvertens requested changes

2021-04-27 22:16 UTC, mvertens commented on config/cesm/config_grids.xml
> +    <model_grid alias="f09_g16_gris4" compset="_CISM">
Are we really still supporting g16? I did not think so. Could you check if moving forwards we just remove this resolution. I am wondering at this point if it should totally be removed from config_grids.xml for cesm. At any rate - it certainly does not make sense to add a new item for CISM for it if we are no longer supporting it.

2021-04-27 22:16 UTC, mvertens commented on config/cesm/config_grids.xml
> +    <model_grid alias="f09_g16_gris20" compset="_CISM">
Same comment as above for g16.

2021-04-27 22:16 UTC, mvertens commented on config/cesm/config_grids.xml
> +    <model_grid alias="f19_g16_gris4" compset="_CISM">
Same comment for g16.

2021-04-27 22:16 UTC, mvertens commented on config/cesm/config_grids_common.xml
> +    <gridmap ocn_grid="gx1v6" glc_grid="gris4" >
See comment for g16 above.

2021-04-27 22:16 UTC, mvertens commented on config/cesm/config_grids_common.xml
> +    <gridmap ocn_grid="gx1v6" glc_grid="gris20" >
See comment for g16 above.

2021-04-27 22:28 UTC, billsacks commented
A grep for "g16" across all CESM test lists shows 99 tests still using g16. Granted, these are mostly / all A, X, C and G compsets. My feeling was that it is easiest, both now and down the line, to just keep things consistent in this PR, and then we can remove all of the g16 in one fell swoop later. That said, if you prefer that I limit the additions of g16, a compromise could be avoiding adding new aliases involving g16 – but I think I still need to make some of the changes in this PR that refer to g16 until we are really ready to remove that grid. Let me know what you think.

2021-04-27 22:38 UTC, billsacks commented
Okay, I just pushed a change where I removed some g16 grid aliases.

2021-04-27 22:40 UTC, mvertens approved these changes

2021-04-27 23:02 UTC, billsacks commented
This cime change depends on the CISM changes in https://github.com/ESCOMP/CISM-wrapper/pull/58. I plan to bring that PR to cism master soon, but I think this cime PR should wait to come to master until we're ready within CESM to bring in the CISM changes, which might be a few weeks.

2021-04-28 00:40 UTC, jedwards4b commented
@billsacks in that case I suggest using "Convert to draft"

2021-04-28 12:33 UTC, billsacks commented
Converting to draft to signal that we aren't ready to merge this (though it's complete and ready to merge once we're ready on the CESM side).

2021-05-10 05:11 UTC, merged