Modify ERI test for EAM
ESMCI/cime pull request #3963
Opened 2021-05-11 21:55 UTC by rljacob

ERI will edit user_nl_cam to run.  Need to optionally
edit user_nl_eam (if it exists).

Test suite: ERI.ne4_ne4.FC5AV1C-L
Test baseline:  none
Test namelist changes:  none
Test status: BFB

2021-05-11 22:15 UTC, jedwards4b requested changes

2021-05-11 22:15 UTC, jedwards4b commented on scripts/lib/CIME/SystemTests/eri.py
> +        if os.path.exists("user_nl_eam"):
how about:
```
  for model in ["cam", "eam"]:
    user_nl = "user_nl_{}".format(model)
    if os.path.exists(user_nl):
      if "inithist" not in open(user_nl, "r").read():
        with open(user_nl, "a") as fd:
          fd.write("inithist = 'ENDOFRUN'\n")
```

2021-05-12 03:23 UTC, rljacob commented
@jedwards4b changed it to your version and force-pushed to remove my other version.

2021-05-12 03:29 UTC, rljacob commented
Related issue #3964

2021-05-12 13:08 UTC, jedwards4b approved these changes

2021-05-12 13:09 UTC, jedwards4b commented
Pylint issue:
```
======================================================================
FAIL: test_pylint_scripts_lib_CIME_SystemTests_eri_py (__main__.B_CheckCode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 3497, in test
    self.assertTrue(result == "", msg=result)
AssertionError: False is not true : ************* Module CIME.SystemTests.eri
scripts/lib/CIME/SystemTests/eri.py:117:0: W0311: Bad indentation. Found 10 spaces, expected 12 (bad-indentation)
scripts/lib/CIME/SystemTests/eri.py:118:0: W0311: Bad indentation. Found 10 spaces, expected 12 (bad-indentation)
scripts/lib/CIME/SystemTests/eri.py:119:0: W0311: Bad indentation. Found 12 spaces, expected 16 (bad-indentation)
scripts/lib/CIME/SystemTests/eri.py:120:0: W0311: Bad indentation. Found 14 spaces, expected 20 (bad-indentation)
scripts/lib/CIME/SystemTests/eri.py:121:0: W0311: Bad indentation. Found 16 spaces, expected 24 (bad-indentation)
```

2021-05-12 17:00 UTC, rljacob commented
Can I run pylint on the command line to check that I have it right?

2021-05-12 17:05 UTC, jedwards4b commented
scripts_regression_tests.py runs pylint as one of its tests.  You should have run it as a step in submitting the PR.  But you can also run cime/scripts/Tools/code_checker eri.py

2021-05-12 17:47 UTC, billsacks commented on scripts/lib/CIME/SystemTests/eri.py
> +          user_nl = "user_nl_{}".format(model)
Just for informational purposes (doesn't need to be fixed for this PR): this doesn't handle multi-instance cases. There is a more general function here https://github.com/esmci/cime/blob/master/scripts/lib/CIME/SystemTests/test_utils/user_nl_utils.py#L8 that handles multi-instance, but that function would need to be extended if you want to replicate all of the logic here, including something like an optional argument to return quietly if the given file doesn't exist.

2021-05-12 22:16 UTC, rljacob commented
pylint issues fixed.  Had to get pylint installed on my dev platform.

2021-05-13 17:57 UTC, merged