Adds CASE_HASH to env_case
ESMCI/cime pull request #3968
Opened 2021-05-14 16:50 UTC by jasonb5

Adds CASH_HASH to env_case.xml. The hash is made up of 
create_newcase arguments, date/time, user, and hostname. This
is meant to be finer grain than case-group for case databases.

Test suite: scripts_regression_tests.py
Test baseline: n/a
Test namelist changes: n/a
Test status: bit for bit

Fixes #3944 

User interface changes?: n/a
Update gh-pages html (Y/N)?: n/a

2021-05-14 17:21 UTC, rljacob commented
Now if there are several submissions from the same CASEDIR, they will all have the same hash and the provenance system can identify them as being from the same case.  

But I'm now wondering what we should do if a user needs to re-run create_newcase to continue the same simulation.  Maybe they moved it to a different machine.   @sarats what do you think?

2021-05-14 17:48 UTC, jedwards4b requested changes
What is the exact intent here?  I generated a case and then ran create_clone to create a new case.  Both cases have the same CASE_HASH - I don't think that is the intent.

2021-05-14 17:54 UTC, rljacob commented
That's true, the hashes should be different then.

2021-05-14 19:01 UTC, jasonb5 commented
Fixed it so anytime `Case.copy` is called a new hash is generated. This covers `create_clone` and if called explicitly via a script (more of a future case).

2021-05-14 19:56 UTC, jedwards4b approved these changes

2021-05-17 18:56 UTC, merged

2026-03-05 00:02 UTC, rljacob commented
@jasonb5 is "case.copy" getting called when case.submit or case.build is called?   We're trying to use this and seeing the CASE_HASE change with every submission.