Add chksum argument
ESMCI/cime pull request #3977
Opened 2021-05-21 22:46 UTC by jasonb5

Adds --chksum argument to case.submit and create_test allowing 
users to verify checksums without explicitly calling 
check_input_data with --chksum.

Test suite: scripts_regression_tests.py
Test baseline: n/a
Test namelist changes: n/a 
Test status: bit for bit

Fixes #3467 

User interface changes?: n/a
Update gh-pages html (Y/N)?: N

2021-05-24 19:21 UTC, jgfouca approved these changes

2021-06-01 14:23 UTC, jedwards4b requested changes
minor whitespace change request, otherwise looks good.

2021-06-01 14:23 UTC, jedwards4b commented on scripts/lib/CIME/tests/test_case.py
> +
remove whitespace here.

2021-06-02 16:44 UTC, jedwards4b approved these changes

2021-06-03 14:25 UTC, merged