update github action remove pnetcdf and fix pylint issues
ESMCI/cime pull request #4395
Opened 2023-04-17 14:56 UTC by jedwards4b

Update the github action to use the pnetcdf installed with apt-get

Test suite:
Test baseline:
Test namelist changes:
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

2023-04-17 21:33 UTC, jedwards4b commented
@fischer-ncar This PR gets the srt working again in the github workflow for maint-5.6

2023-04-18 15:43 UTC, fischer-ncar requested changes

2023-04-18 15:43 UTC, fischer-ncar commented on .github/workflows/srt.yml
> +          sudo apt-get install libxml2-utils wget gfortran openmpi-bin netcdf-bin libopenmpi-dev cmake libnetcdf-dev pylint
Based on the title of the PR, shouldn't pnetcdf be in apt-get call?  But looking at you commit comments, you're not using pnetcdf.  So the title of the PR should be updated.

2023-04-18 15:46 UTC, jedwards4b commented
@fischer-ncar title changed, thanks.

2023-04-18 15:47 UTC, fischer-ncar approved these changes

2023-04-18 15:50 UTC, merged