Feature/long grid name
ESMCI/cime pull request #4615
Opened 2024-04-15 13:27 UTC by jedwards4b

allows the complete long grid name as an argument to create_newcase

Test suite:
Test baseline:
Test namelist changes:
Test status: bit for bit
Fixes 

User interface changes?:

Update gh-pages html (Y/N)?:

2024-04-15 20:07 UTC, jasonb5 requested changes

2024-04-16 07:07 UTC, gold2718 commented on .gitmodules
> +	url = https://github.com/ESMCI/cprnc
Doesn't this suggested change require anyone trying to use CIME to have a GitHub account with registered SSH keys? That is not currently a requirement for CESM, is it for E3SM?

2024-04-16 12:13 UTC, jedwards4b commented on .gitmodules
> +	url = https://github.com/ESMCI/cprnc
Yes, we have discussed this - e3sm requires the ssh protocol for jenkins and cesm is currently using a branch of cime using https, the git-fleximod will handle this correctly without a branch so creating this branch is a temporary requirement for cesm.

2024-04-18 22:28 UTC, jasonb5 approved these changes
LGTM

2024-04-24 09:18 UTC, mvertens approved these changes
Thanks Jim. I've tested this and it looks good. This will be super useful to have.

2024-04-24 13:24 UTC, jedwards4b commented on CIME/XML/grids.py
> +    def _valid_lname(self, name):
I ran SMS_Ln9.T42z30_T42_mg17.FHS94.derecho_intel and SMS_Ln9.a%T42z30_l%null_oi%null_r%null_g%null_w%null_z%null_m%gx1v7.2000_CAM%HS94_SLND_SICE_SOCN_SROF_SGLC_SWAV_SESP.derecho_intel  and compared results.  They are identical.

2024-04-24 13:29 UTC, merged